---
title: "Laboratorio 4"
author: "Fausto Holcombe 20170476"
date: "8/28/2019"
output: rmarkdown::github_document
---

```{r, cache = TRUE}
library(tidyr)
library(reshape2)
library(plyr)
library(dplyr)
library(stringr)
```

```{r, cache = TRUE}
df <- data.frame(row = LETTERS[1:3], a = 1:3, b = 4:6, c = 7:9)
dfm <- melt(df, id = "row")
dfg <- gather(df,key ="variable",value = "value",a:c)
```

```{r, cache = TRUE}
poblacion <- read.csv('raw.csv')
poblacion <- poblacion[-1]
poblacion <- poblacion %>% 
  melt(id = c("country","year"))
poblacion$sexo <- substring(poblacion$variable,0,1)
poblacion$edad <- substring(poblacion$variable,2)
poblacion$variable <- NULL
poblacion$edad <- revalue(poblacion$edad, c("014" = "0-14", "1524" = "15-24", "2534" = "25-34","3544" = "35-44","4554" = "45-54","5564" = "55-64", "65" = ">=65", "u" = "UNKWN"))
poblacion <- poblacion %>% select(country,year,gender = sexo,age_group = edad,frequency = value)
head(poblacion)
```

```{r, cache = TRUE}
load('wide_religion.Rda')
wide_religion %>%
  gather(key = "income_level",value = "frequency",-religion) %>% 
  head()
```

